### PR TITLE
Prevent new users/members to be stored in db when invite fails

### LINKED ISSUE #5349: New member shows invited when the email was not sent
### Your environment (Generated via diagnostics page)

* Vaultwarden version: v1.32.7
* Web-vault version: v2024.6.2c
* OS/Arch: linux/x86_64
* Running within a container: true (Base: Debian)
* Database type: SQLite
* Database version: 3.46.0
* Environment settings overridden!: false
* Uses a reverse proxy: false
* Internet access: true
* Internet access via a proxy: false
* DNS Check: true
* Browser/Server Time Check: true
* Server/NTP Time Check: true
* Domain Configuration Check: false
* HTTPS Check: false
* Websocket Check: true
* HTTP Response Checks: true

### Config & Details (Generated via diagnostics page)

<details><summary>Show Config & Details</summary>

**Config:**

```json
{
  "_duo_akey": null,
  "_enable_duo": true,
  "_enable_email_2fa": true,
  "_enable_smtp": true,
  "_enable_yubico": true,
  "_icon_service_csp": "",
  "_icon_service_url": "",
  "_ip_header_enabled": true,
  "_max_note_size": 10000,
  "_smtp_img_src": "***:",
  "admin_ratelimit_max_burst": 3,
  "admin_ratelimit_seconds": 300,
  "admin_session_lifetime": 20,
  "admin_token": "***",
  "allowed_connect_src": "",
  "allowed_iframe_ancestors": "",
  "attachments_folder": "data/attachments",
  "auth_request_purge_schedule": "30 * * * * *",
  "authenticator_disable_time_drift": false,
  "data_folder": "data",
  "database_conn_init": "",
  "database_max_conns": 10,
  "database_timeout": 30,
  "database_url": "***************",
  "db_connection_retries": 15,
  "disable_2fa_remember": false,
  "disable_admin_token": false,
  "disable_icon_download": false,
  "domain": "****://*********",
  "domain_origin": "****://*********",
  "domain_path": "",
  "domain_set": true,
  "duo_context_purge_schedule": "30 * * * * *",
  "duo_host": null,
  "duo_ikey": null,
  "duo_skey": null,
  "duo_use_iframe": false,
  "email_2fa_auto_fallback": false,
  "email_2fa_enforce_on_verified_invite": false,
  "email_attempts_limit": 3,
  "email_change_allowed": true,
  "email_expiration_time": 600,
  "email_token_size": 6,
  "emergency_access_allowed": true,
  "emergency_notification_reminder_schedule": "0 3 * * * *",
  "emergency_request_timeout_schedule": "0 7 * * * *",
  "enable_db_wal": true,
  "enable_websocket": true,
  "enforce_single_org_with_reset_pw_policy": false,
  "event_cleanup_schedule": "0 10 0 * * *",
  "events_days_retain": null,
  "experimental_client_feature_flags": "fido2-vault-credentials",
  "extended_logging": true,
  "helo_name": null,
  "hibp_api_key": null,
  "http_request_block_non_global_ips": true,
  "http_request_block_regex": null,
  "icon_blacklist_non_global_ips": true,
  "icon_blacklist_regex": null,
  "icon_cache_folder": "data/icon_cache",
  "icon_cache_negttl": 259200,
  "icon_cache_ttl": 2592000,
  "icon_download_timeout": 10,
  "icon_redirect_code": 302,
  "icon_service": "internal",
  "incomplete_2fa_schedule": "30 * * * * *",
  "incomplete_2fa_time_limit": 3,
  "increase_note_size_limit": false,
  "invitation_expiration_hours": 120,
  "invitation_org_name": "Vaultwarden",
  "invitations_allowed": true,
  "ip_header": "X-Real-IP",
  "job_poll_interval_ms": 30000,
  "log_file": null,
  "log_level": "info",
  "log_timestamp_format": "%Y-%m-%d %H:%M:%S.%3f",
  "login_ratelimit_max_burst": 10,
  "login_ratelimit_seconds": 60,
  "org_attachment_limit": null,
  "org_creation_users": "",
  "org_events_enabled": false,
  "org_groups_enabled": false,
  "password_hints_allowed": true,
  "password_iterations": 600000,
  "push_enabled": false,
  "push_identity_uri": "https://identity.bitwarden.com",
  "push_installation_id": "***",
  "push_installation_key": "***",
  "push_relay_uri": "https://push.bitwarden.com",
  "reload_templates": false,
  "require_device_email": false,
  "rsa_key_filename": "data/rsa_key",
  "send_purge_schedule": "0 5 * * * *",
  "sendmail_command": null,
  "sends_allowed": true,
  "sends_folder": "data/sends",
  "show_password_hint": false,
  "signups_allowed": true,
  "signups_domains_whitelist": "",
  "signups_verify": false,
  "signups_verify_resend_limit": 6,
  "signups_verify_resend_time": 3600,
  "smtp_accept_invalid_certs": false,
  "smtp_accept_invalid_hostnames": false,
  "smtp_auth_mechanism": null,
  "smtp_debug": false,
  "smtp_embed_images": true,
  "smtp_explicit_tls": null,
  "smtp_from": "****************************",
  "smtp_from_name": "Vaultwarden",
  "smtp_host": "**************",
  "smtp_password": "***",
  "smtp_port": 465,
  "smtp_security": "force_tls",
  "smtp_ssl": null,
  "smtp_timeout": 15,
  "smtp_username": "****************************",
  "templates_folder": "data/templates",
  "tmp_folder": "data/tmp",
  "trash_auto_delete_days": null,
  "trash_purge_schedule": "0 5 0 * * *",
  "use_sendmail": false,
  "use_syslog": false,
  "user_attachment_limit": null,
  "user_send_limit": null,
  "web_vault_enabled": true,
  "web_vault_folder": "web-vault/",
  "yubico_client_id": null,
  "yubico_secret_key": null,
  "yubico_server": null
}
```

</details>

### Vaultwarden Build Version

1.32.7

### Deployment method

Official Container Image

### Custom deployment method

_No response_

### Reverse Proxy

N/A

### Host/Server Operating System

Linux

### Operating System Version

Debian

### Clients

Web Vault

### Client Version

_No response_

### Steps To Reproduce

Fresh deployment with for example an incorrect app password for Gmail SMTP, create an org, add a user, it will send an email but give an error because the app password is wrong, but the members page will show the new member as invited when they are not

### Expected Result

The new member is not in the database and not shown as invited

### Actual Result

The member is shown as invited

### Logs

_No response_

### Screenshots or Videos

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by BlackDex**
Currently when a (new) user gets invited as a member to an org, and SMTP is enabled, but sending the invite fails, the user is still created.
They will only not have received a mail, and admins/owners need to re-invite the member again.
Since the dialog window still keeps on-top when this fails, it kinda invites to click try again, but that will fail in mentioning the user is already a member.

To prevent this weird flow, this commit will delete the user, invite and member if sending the mail failed.
This allows the inviter to try again if there was a temporary hiccup for example, or contact the server admin and does not leave stray users/members around.

Fixes #5349

### CODE REVIEW

**Comment by stefan0xC** [comment]
What about the CollectionUser records? Wouldn't they need to be deferred as well?

**Comment by BlackDex** [comment]
> What about the CollectionUser records? Wouldn't they need to be deferred as well?

Ah yes that needs to be moved to.

**Comment by BlackDex** [comment]
I also wonder if this is the right way to go btw.
Now i defer saving the objects, but that could also mean, that after sending an email, storing the objects might fail, which i think is far worse then not being able to sent out an email.

I think it's better to save the objects, and upon mail failure, delete the items.

The only thing i would then put after sending an email is adding the user to the groups and collections.

**Comment by BlackDex** [comment]
Ok, I made some changes. Instead of deferring, I now delete the records if sending the mail fails.
While this will cause some extra db queries to be executed, I do not think this will happen that much, and still keeps things more as they were.

I did moved creating the groups and collection records to after sending the mail, as those need the other records anyway.

File: src/api/core/organizations.rs [hunk 1]
```diff
@@ -929,11 +930,49 @@ async fn send_invite(org_id: &str, data: Json<InviteData>, headers: AdminHeaders
...
+                Some(headers.user.email.clone()),
+            )
+            .await
+            {
+                // Upon error delete the user, invite and org member records when needed
+                if user_created {
+                    Invitation::take(email, &mut conn).await;
+                    user.delete(&mut conn).await?;
+                }
+                new_member.delete(&mut conn).await?;
```
Comment (stefan0xC) [inline src/api/core/organizations.rs:960]: I would either call `new_member.delete()` before the `if` statement or only in an `else` block because `user.delete()` should also delete the `UserOrganization` and even if it works it feels wrong to call `update_uuid_revision` after deleting the `User`  https://github.com/dani-garcia/vaultwarden/blob/ef4bff09eb4414117cd8ea25c809988872e2016b/src/db/models/organization.rs#L708-L709

Comment (stefan0xC) [reply src/api/core/organizations.rs:960]: Oh, and Invitation::take() is also called by user.delete, so this probably can be simplified to just 
```suggestion
                if user_created {
                    user.delete(&mut conn).await?;
                } else {
                    new_member.delete(&mut conn).await?;
                }
```

Comment (BlackDex) [reply src/api/core/organizations.rs:960]: Uch, I should get some more sleep

Comment (BlackDex) [reply src/api/core/organizations.rs:960]: Besides all that, Invites are also only created if smtp is **not** enabled 🤣 , so that would have resulted in a useless query anyway. While it still is done upon deleting the user, it's probably the better option.

**Review by stefan0xC — APPROVED** [review]
Looks good to me. Even if it does not prevent sending mails to non-existent hosts.

Not sure if that is something that we can fix because that's something that happens after the mail has been successfully received by the MTA
```
an 07 12:38:23 mx postfix/lmtp[2296669]: 8573C4078F: to=<stefan+mailinvitetest@example.com>, relay=127.0.0.1[127.0.0.1]:10024, delay=5.1, delays=0.28/0.1/0.02/4.7, dsn=2.0.0, status=sent (250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): status=sent (250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as 5703C40709
an 07 12:38:23 mx postfix/qmgr[1824492]: 8573C4078F: removed
an 07 12:38:23 mx postfix/smtp[2296676]: 5703C40709: to=<stefan+mailinvitetest@example.com>, relay=none, delay=0.36, delays=0.09/0.25/0.02/0, dsn=5.1.0, status=bounced (Domain example.com does not accept mail (nullMX))
```

**Comment by BlackDex** [comment]
That will be difficult indeed, also, sometimes MTA's use graylogging, which could cause these kind of messages.
Thanks for testing and reviewing!
