### PR TITLE
Fix External ID not set during DC Sync

### LINKED ISSUE #3777: No external user ID created when using bwdc and user already has an account
### Subject of the issue

I user Bitwarden directory connector (v2022.11.0) to sync my AD users and groups into my Organisation.
Thereby I noticed that users who already have an account do not get an external id. 
This seems to be independent of whether the account already exists because the user is using the private vault and is not yet part of an organization or the user has already been manually invited to the organization.

### Your environment (Generated via diagnostics page)
* Vaultwarden version: v1.29.1
* Web-vault version: v2023.5.0
* OS/Arch: linux/x86_64
* Running within Docker: true (Base: Debian)
* Environment settings overridden: false
* Uses a reverse proxy: true
* IP Header check: true (X-Real-IP)
* Internet access: true
* Internet access via a proxy: false
* DNS Check: true
* Browser/Server Time Check: true
* Server/NTP Time Check: true
* Domain Configuration Check: true
* HTTPS Check: true
* Database type: SQLite
* Database version: 3.41.2
* Clients used: 
* Reverse proxy and version: 
* Other relevant information: 

### Config (Generated via diagnostics page)
<details><summary>Show Running Config</summary>

**Environment settings which are overridden:** 

```json
{
  "_duo_akey": null,
  "_enable_duo": false,
  "_enable_email_2fa": true,
  "_enable_smtp": true,
  "_enable_yubico": false,
  "_icon_service_csp": "",
  "_icon_service_url": "",
  "_ip_header_enabled": true,
  "_smtp_img_src": "cid:",
  "admin_ratelimit_max_burst": 3,
  "admin_ratelimit_seconds": 300,
  "admin_session_lifetime": 20,
  "admin_token": "***",
  "allowed_iframe_ancestors": "",
  "attachments_folder": "data/attachments",
  "authenticator_disable_time_drift": false,
  "data_folder": "data",
  "database_conn_init": "",
  "database_max_conns": 10,
  "database_timeout": 30,
  "database_url": "***************",
  "db_connection_retries": 15,
  "disable_2fa_remember": false,
  "disable_admin_token": false,
  "disable_icon_download": false,
  "domain": "*****://**********************",
  "domain_origin": "*****://**********************",
  "domain_path": "",
  "domain_set": true,
  "duo_host": null,
  "duo_ikey": null,
  "duo_skey": null,
  "email_attempts_limit": 3,
  "email_expiration_time": 600,
  "email_token_size": 6,
  "emergency_access_allowed": true,
  "emergency_notification_reminder_schedule": "0 3 * * * *",
  "emergency_request_timeout_schedule": "0 7 * * * *",
  "enable_db_wal": true,
  "event_cleanup_schedule": "0 10 0 * * *",
  "events_days_retain": 60,
  "extended_logging": true,
  "helo_name": null,
  "hibp_api_key": null,
  "icon_blacklist_non_global_ips": false,
  "icon_blacklist_regex": null,
  "icon_cache_folder": "data/icon_cache",
  "icon_cache_negttl": 259200,
  "icon_cache_ttl": 2592000,
  "icon_download_timeout": 10,
  "icon_redirect_code": 302,
  "icon_service": "internal",
  "incomplete_2fa_schedule": "30 * * * * *",
  "incomplete_2fa_time_limit": 3,
  "invitation_expiration_hours": 336,
  "invitation_org_name": "Bitwarden",
  "invitations_allowed": true,
  "ip_header": "X-Real-IP",
  "job_poll_interval_ms": 30000,
  "log_file": "/data/vaultwarden.log",
  "log_level": "warn",
  "log_timestamp_format": "%Y-%m-%d %H:%M:%S.%3f",
  "login_ratelimit_max_burst": 10,
  "login_ratelimit_seconds": 60,
  "org_attachment_limit": null,
  "org_creation_users": "***********************",
  "org_events_enabled": true,
  "org_groups_enabled": true,
  "password_hints_allowed": true,
  "password_iterations": 100000,
  "push_enabled": false,
  "push_installation_id": "***",
  "push_installation_key": "***",
  "push_relay_uri": "https://push.bitwarden.com",
  "reload_templates": false,
  "require_device_email": false,
  "rsa_key_filename": "data/rsa_key",
  "send_purge_schedule": "0 5 * * * *",
  "sendmail_command": null,
  "sends_allowed": false,
  "sends_folder": "data/sends",
  "show_password_hint": false,
  "signups_allowed": false,
  "signups_domains_whitelist": "",
  "signups_verify": true,
  "signups_verify_resend_limit": 6,
  "signups_verify_resend_time": 3600,
  "smtp_accept_invalid_certs": false,
  "smtp_accept_invalid_hostnames": false,
  "smtp_auth_mechanism": null,
  "smtp_debug": false,
  "smtp_embed_images": true,
  "smtp_explicit_tls": null,
  "smtp_from": "**********************",
  "smtp_from_name": "Bitwarden",
  "smtp_host": "*************",
  "smtp_password": null,
  "smtp_port": 25,
  "smtp_security": "off",
  "smtp_ssl": null,
  "smtp_timeout": 15,
  "smtp_username": null,
  "templates_folder": "data/templates",
  "tmp_folder": "data/tmp",
  "trash_auto_delete_days": 14,
  "trash_purge_schedule": "0 5 0 * * *",
  "use_sendmail": false,
  "use_syslog": false,
  "user_attachment_limit": null,
  "web_vault_enabled": true,
  "web_vault_folder": "web-vault/",
  "websocket_address": "0.0.0.0",
  "websocket_enabled": false,
  "websocket_port": 3012,
  "yubico_client_id": null,
  "yubico_secret_key": null,
  "yubico_server": null
}
```
</details>

### Steps to reproduce

Case 1: A user without an account in this Vaultwarden instance is added to an organization via bwdc.
The user is invited and External ID is set successfully.

Case 2: A user with an existing account in this Vaultwarden instance is added to an organization via bwdc.
The user is invited and added to the organization, but no External ID is set.

Case 3: A user who is already part of my organization is to be subsequently managed by bwdc and given an External ID. After synchronization the user seems to be untouched. No External ID has been set.

### Expected behaviour
In every case an External ID should be assigned to the user. 
Even if the user already exists, an external ID should be assigned, otherwise the permission assignment between Vaultwarden and AD groups will not work.

If this is an issue in bwdc, is there a way to manually assign the External ID?

### PR DESCRIPTION
**Pull request by BlackDex**
While working on the fix for #3777 I realized the location where the `external_id`
is stored was wrong. It was stored in the `users` table, but it actually
should have been stored in the `users_organizations` table.

This will move the column to the right table. It will not move the
values of the `external_id` column, because if there are more
organizations, there is no way to really know which organization it is
linked to. Setups using the Directory Connector can clear the sync
cache, and sync again, that will store all the `external_id` values at
the right location.

Also changed the function to revoke,restore an org-user and set_external_id to return a boolean.
It will state if the value has been changed or not, and if not, we can
prevent a `save` call to the database.

The `users` table is not changed to remove the `external_id` column, thi
to prevent issue when users want to revert back to an earlier version
for some reason. We can do this after a few minor release i think.

Fixes #3777

### CODE REVIEW

File: src/api/core/public.rs [hunk 1]
```diff
@@ -68,12 +70,23 @@ async fn ldap_import(data: JsonUpcase<OrgImportData>, token: PublicToken, mut co
                 user_org.restore();
                 user_org.save(&mut conn).await?;
             }
+
+            // Set external_id if the user is restored.
+            if let Some(mut user) = user {
+                user.set_external_id(Some(user_data.ExternalId.clone()));
+                user.save(&mut conn).await?;
```
Comment (dani-garcia) [inline src/api/core/public.rs:77]: I imagine most users are going to keep the same external_id if they already have it, would it be worth it to only save the user when the external_id is different to save some db operations?

Comment (BlackDex) [reply src/api/core/public.rs:77]: Well, i did some looking just quick, and we store it in the wrong place it looks like.
This actually needs to be stored in the user_org, which i already had a feeling of being better but it is also how Bitwarden does it.

It is of course possible to use the Directory Connector for multiple Org entities within the same company and a user could be part of multiple, this way it would overwrite all items no matter which org/directory-connector does the sync.

Maybe we need to change this. But the problem here will be that we can't really migrate the external_id to the correct org, since we don't know which org did the sync, and which is correct.

While, technically it shouldn't matter, since it is only for display purpose as far as i know at the moment.
Nothing yet which uses this value in the code.

**Comment by BlackDex** [comment]
Converted to a draft. I have the code fixed, but i need to do the SQL migrations and testing before this can be merged.

I'm moving the external_id into the user_org table.

File: src/api/core/public.rs (hunk 1 above)
Comment (BlackDex) [reply src/api/core/public.rs]: @dani-garcia, i have modified the PR so it will move the `external_id` column to the `users_organizations` table instead of the `users` table. This fixes issues with multiple different orgs synced to the same instance.

I also made it so that it will only save the record when needed.

**Comment by BlackDex** [comment]
The only thing i encountered is, that you can't revert back that easily after this PR has been merged to a previous version.
The reason is we have removed a column from the users table which causes an issue with older versions.

This makes me wonder what we should do here?
Leave the column there for a while, and create some tech-debt ticket/todo to remove it in the future say, x new minor release, or x date or something?

@dani-garcia what do you think?

**Comment by stefan0xC** [comment]
Since we in general don't support downgrading I think we could remove the column the next release after the release with this PR (so if there should be an issue they can roll back to the latest working release). Provided that the next release fixes the `armv6` issue which currently compels users to downgrade back to `1.29.1`. Otherwise we should probably delay removing the column for another release (or warn affected users to use the `-alpine` images images instead because downgrading to a previous version - especially one without this change - might require a manual restore of the column).

**Comment by BlackDex** [comment]
I agree, lets remove the deletion of the column for now.

**Review by dani-garcia — APPROVED** [review]
