### PR TITLE
Fix issue when using uppercase chars in emails

### LINKED ISSUE #1963: Inviting users with capital letters in there mail address without mail enabled will fail to register
Inviting users with capital letters in there mail address without mail enabled will fail to register

see Matrix chat for more information

### PR DESCRIPTION
**Pull request by BlackDex**
In the case when SMTP is disabled and.
when inviting new users either via the admin interface or into an
organization and using uppercase letters, this would fail for those
users to be able to register since the checks which were done are
case-sensitive and never matched.

This PR fixes that issue by ensuring everything is lowercase.
Fixes #1963

### CODE REVIEW

File: src/api/core/accounts.rs [hunk 1]
```diff
@@ -62,11 +62,12 @@ struct KeysData {
 #[post("/accounts/register", data = "<data>")]
 fn register(data: JsonUpcase<RegisterData>, conn: DbConn) -> EmptyResult {
     let data: RegisterData = data.into_inner().data;
+    let reg_email = data.Email.to_lowercase();
```
Comment (jjlin) [inline src/api/core/accounts.rs:65]: Any particular reason `reg_email` isn't just called `email`?

File: src/api/core/organizations.rs [hunk 2]
```diff
@@ -539,19 +539,20 @@ fn send_invite(org_id: String, data: JsonUpcase<InviteData>, headers: AdminHeade
         err!("Only Owners can invite Managers, Admins or Owners")
     }
 
-    for email in data.Emails.iter() {
+    for mail in data.Emails.iter() {
```
Comment (jjlin) [inline src/api/core/organizations.rs:542]: I think it would be cleaner to just call this `email` and have it shadowed by the `let email` below, instead of making up different names unnecessarily.

File: src/db/models/user.rs [hunk 3]
```diff
@@ -349,7 +349,8 @@ impl User {
 }
 
 impl Invitation {
-    pub const fn new(email: String) -> Self {
+    pub fn new(mail: String) -> Self {
```
Comment (jjlin) [inline src/db/models/user.rs:352]: Same here, the original `email` is fine

File: src/api/core/accounts.rs (hunk 1 above)
Comment (BlackDex) [reply src/api/core/accounts.rs:65]: No not really actually, ill change that indeed.

File: src/api/core/organizations.rs (hunk 2 above)
Comment (BlackDex) [reply src/api/core/organizations.rs:542]: Well, i wanted to follow the same line as is done with the new user fn. But i guess it can be changed there too.

File: src/db/models/user.rs (hunk 3 above)
Comment (BlackDex) [reply src/db/models/user.rs:352]: Same as above.

**Comment by BlackDex** [comment]
@jjlin Fixed the remarks :)
