### PR TITLE
Fix v2025.6.x clients and newer to delete items

### LINKED ISSUE #6003: Red trash can missing to delete in Browserextension MS Edge/Chrome Version 2025.6.0
### Discussed in https://github.com/dani-garcia/vaultwarden/discussions/5996

<div type='discussions-op-text'>

<sup>Originally posted by **Lausbua** June 28, 2025</sup>
Hello,

i'm alone with my problem?
After automatic update browser extensions MS Edge/Google Chrome to version 2025.6.0 SDK: 'main (1fa0f7a)' i lost my red trash can icon in the bottom right corner. I can't see it either in view or edit mode.

image

In Firefox the extension is 2025.5.0 and i can delete any entry in my personal vault.
The red trash can is visible and usable.

image

The webclient and ios app isn't broke everything is fine and i can delete without problems.

I use a personal vault, no organisation oder family thing.
I reinstall multiple times and try it on another computer.

</div>

### PR DESCRIPTION
**Pull request by BlackDex**
The new v2025.6.1 clients need the new `permissions` key/value to support deleting. By using the same flag as the current `edit` key/value we can fix this.

More fine-grained control is something we should still code, so for not this should solve those issues

Fixes #6003
Fixes #5996

### CODE REVIEW

File: src/db/models/cipher.rs [hunk 1]
```diff
@@ -382,6 +382,11 @@ impl Cipher {
             // the "Read Only" or "Hide Passwords" restrictions for the user.
             json_object["edit"] = json!(!read_only);
             json_object["viewPassword"] = json!(!hide_passwords);
+            // The new key used by clients since v2025.6.1
```
Comment (stefan0xC) [inline src/db/models/cipher.rs]: LGTM. Only this comment bugs me a bit:

```suggestion
            // The new key used by clients since v2025.6.0
```

For most clients it's `v2025.6.0`, cf. https://github.com/dani-garcia/vaultwarden/discussions/5996#discussioncomment-13610267 and https://github.com/bitwarden/clients/commit/b5bddd0b06b9a05dedd02197d9aaa7fd0ff2b3c7 :nerd_face:  
image

**Review by stefan0xC — APPROVED** [review]

File: src/db/models/cipher.rs (hunk 1 above)
Comment (BlackDex) [reply src/db/models/cipher.rs]: Ah, it's since .0 then,  only the web-vault since .1

**Review by stefan0xC — APPROVED** [review]

**Review by dani-garcia — APPROVED** [review]
LGTM, This has some reqsign dependency updates that have conflicts now

**Review by dani-garcia — APPROVED** [review]

**Comment by grtessman** [comment]
Is this in `vaultwarden/server:latest` yet?  I just installed latest and still have this problem.

**Comment by stefan0xC** [comment]
No, only in `testing`.  You can also check a commit if it has a tagged release
[image](https://github.com/dani-garcia/vaultwarden/commit/3b48e6e90386bcee3e8a2b99ec2472cba979adf1)

**Comment by grtessman** [comment]
> can also check a commit if has a tagged relea

Thank you for the fix - I'll keep an eye out for an updated tag for the release.

**Comment by Chaniug** [comment]
There is no problem on testing, and the delete button can be displayed normally. But laster，there are still problems
