### PR TITLE
Fix wrong display of MFA email.

### LINKED ISSUE #1878: Verification Code Sent to Old Email
### Subject of the issue

I changed my email successfully, and verified the new email. However, when I try to login using 2FA, the verification code is sent to the old one.

I tried to re-enable the email 2FA, and it showed me a message that the code will be sent to the new email. But it's still sent to the old one.

### Deployment environment

* Vaultwarden version: v1.22.2
* Web-vault version: v2.21.1
* Running within Docker: true
* Environment settings overridden: true
* Uses a reverse proxy: true
* IP Header check: true (X-Forwarded-For)
* Internet access: true
* Internet access via a proxy: false
* DNS Check: true
* Time Check: true
* Domain Configuration Check: true
* HTTPS Check: true
* Database type: SQLite
* Database version: 3.35.4
* Clients used: 
* Reverse proxy and version: 
* Other relevant information: 

### Config (Generated via diagnostics page)
<details><summary>Show Running Config</summary>

**Environment settings which are overridden:** DOMAIN, SIGNUPS_ALLOWED, INVITATIONS_ALLOWED, SHOW_PASSWORD_HINT, ADMIN_TOKEN, SMTP_HOST, SMTP_SSL, SMTP_PORT, SMTP_FROM, SMTP_USERNAME, SMTP_PASSWORD

```json
{
  "_duo_akey": null,
  "_enable_duo": false,
  "_enable_email_2fa": true,
  "_enable_smtp": true,
  "_enable_yubico": true,
  "_ip_header_enabled": true,
  "admin_token": "***",
  "allowed_iframe_ancestors": "",
  "attachments_folder": "data/attachments",
  "authenticator_disable_time_drift": false,
  "data_folder": "data",
  "database_max_conns": 10,
  "database_url": "****/**.*******",
  "db_connection_retries": 15,
  "disable_2fa_remember": false,
  "disable_admin_token": false,
  "disable_icon_download": false,
  "domain": "*****://**.******************.***",
  "domain_origin": "*****://**.******************.***",
  "domain_path": "",
  "domain_set": true,
  "duo_host": null,
  "duo_ikey": null,
  "duo_skey": null,
  "email_attempts_limit": 3,
  "email_expiration_time": 600,
  "email_token_size": 6,
  "enable_db_wal": true,
  "extended_logging": true,
  "helo_name": null,
  "hibp_api_key": null,
  "icon_blacklist_non_global_ips": true,
  "icon_blacklist_regex": null,
  "icon_cache_folder": "data/icon_cache",
  "icon_cache_negttl": 259200,
  "icon_cache_ttl": 2592000,
  "icon_download_timeout": 10,
  "invitation_org_name": "Bitwarden_RS",
  "invitations_allowed": true,
  "ip_header": "X-Forwarded-For",
  "job_poll_interval_ms": 30000,
  "log_file": null,
  "log_level": "Info",
  "log_timestamp_format": "%Y-%m-%d %H:%M:%S.%3f",
  "org_attachment_limit": null,
  "org_creation_users": "",
  "password_iterations": 100000,
  "reload_templates": false,
  "require_device_email": false,
  "rsa_key_filename": "data/rsa_key",
  "send_purge_schedule": "0 5 * * * *",
  "sends_allowed": true,
  "sends_folder": "data/sends",
  "show_password_hint": true,
  "signups_allowed": true,
  "signups_domains_whitelist": "",
  "signups_verify": false,
  "signups_verify_resend_limit": 6,
  "signups_verify_resend_time": 3600,
  "smtp_accept_invalid_certs": false,
  "smtp_accept_invalid_hostnames": false,
  "smtp_auth_mechanism": null,
  "smtp_debug": false,
  "smtp_explicit_tls": false,
  "smtp_from": "*********@**.******************.***",
  "smtp_from_name": "Bitwarden_RS",
  "smtp_host": "****.**.*******.***",
  "smtp_password": "***",
  "smtp_port": 587,
  "smtp_ssl": true,
  "smtp_timeout": 15,
  "smtp_username": "*********@**.******************.***",
  "templates_folder": "data/templates",
  "trash_auto_delete_days": null,
  "trash_purge_schedule": "0 5 0 * * *",
  "use_syslog": false,
  "user_attachment_limit": null,
  "web_vault_enabled": true,
  "web_vault_folder": "web-vault/",
  "websocket_address": "0.0.0.0",
  "websocket_enabled": true,
  "websocket_port": 3012,
  "yubico_client_id": null,
  "yubico_secret_key": null,
  "yubico_server": null
}
```
</details>

* vaultwarden version:

* Install method: Docker image

* Clients used: Web vault

### Steps to reproduce

- Change the email.
- Try to log in with the new email.

### Expected behaviour
Login is successful and verification code is sent to the new email.

### Actual behaviour
Login is successful but verification code is sent to the old email.

### Troubleshooting data

New email in account page:

New email in 2 Step Login option:

Code sent to old email:

### PR DESCRIPTION
**Pull request by BlackDex**
There was some wrong logic regarding the display of which email is
configured to be used for the email MFA. This is now fixed.

Resolves #1878

### CODE REVIEW

**Review by williamdes — APPROVED** [review]

File: src/api/core/two_factor/email.rs [hunk 1]
```diff
@@ -80,17 +80,21 @@ fn get_email(data: JsonUpcase<PasswordData>, headers: Headers, conn: DbConn) ->
...
+                "Enabled": true,
+                "Object": "twoFactorEmail"
+            })))
+        }
+        _ => Ok(Json(json!({
+            "Email": null,
+            "Enabled": false,
+            "Object": "twoFactorEmail"
+        }))),
+    }
```
Comment (jjlin) [inline src/api/core/two_factor/email.rs:97]:
```suggestion
    let (email, enabled) = match TwoFactor::find_by_user_and_type(&user.uuid, TwoFactorType::Email as i32, &conn) {
        Some(x) => {
            let twofactor_data = EmailTokenData::from_json(&x.data)?;
            (json!(twofactor_data.email), true)
        },
        _ => (json!(null), false),
    };

    Ok(Json(json!({
        "Email": email,
        "Enabled": enabled,
        "Object": "twoFactorEmail"
    })))
```

**Review by jjlin — CHANGES_REQUESTED** [review]

File: src/api/core/two_factor/email.rs (hunk 1 above)
Comment (BlackDex) [reply src/api/core/two_factor/email.rs:97]: That is also a possibility.
