### PR TITLE
Fix icon redirect not working on desktop

### LINKED ISSUE #5535: Icon issue still present
### Your environment (Generated via diagnostics page)

* Vaultwarden version: v1.33.1
* Web-vault version: v2025.1.1
* OS/Arch: linux/x86_64
* Running within a container: true (Base: Debian)
* Database type: MySQL
* Database version: 10.11.6-MariaDB-0+deb12u1
* Environment settings overridden!: false
* Uses a reverse proxy: true
* IP Header check: true (X-Real-IP)
* Internet access: true
* Internet access via a proxy: false
* DNS Check: true
* Browser/Server Time Check: true
* Server/NTP Time Check: n/a
* Domain Configuration Check: true
* HTTPS Check: true
* Websocket Check: true
* HTTP Response Checks: true

### Config & Details (Generated via diagnostics page)

<details><summary>Show Config & Details</summary>

**Config:**

```json
{
  "_duo_akey": null,
  "_enable_duo": true,
  "_enable_email_2fa": false,
  "_enable_smtp": true,
  "_enable_yubico": true,
  "_icon_service_csp": "https://www.google.com/s2/favicons?domain= https://*.gstatic.com/favicon",
  "_icon_service_url": "https://www.google.com/s2/favicons?domain={}&sz=32",
  "_ip_header_enabled": true,
  "_max_note_size": 10000,
  "_smtp_img_src": "***:",
  "admin_ratelimit_max_burst": 3,
  "admin_ratelimit_seconds": 300,
  "admin_session_lifetime": 20,
  "admin_token": "***",
  "allowed_connect_src": "",
  "allowed_iframe_ancestors": "",
  "attachments_folder": "data/attachments",
  "auth_request_purge_schedule": "30 * * * * *",
  "authenticator_disable_time_drift": false,
  "data_folder": "data",
  "database_conn_init": "",
  "database_max_conns": 10,
  "database_timeout": 30,
  "database_url": "*****://***********************************************************",
  "db_connection_retries": 15,
  "disable_2fa_remember": false,
  "disable_admin_token": false,
  "disable_icon_download": false,
  "domain": "*****://***************",
  "domain_origin": "*****://***************",
  "domain_path": "",
  "domain_set": true,
  "duo_context_purge_schedule": "30 * * * * *",
  "duo_host": null,
  "duo_ikey": null,
  "duo_skey": null,
  "duo_use_iframe": false,
  "email_2fa_auto_fallback": false,
  "email_2fa_enforce_on_verified_invite": false,
  "email_attempts_limit": 3,
  "email_change_allowed": true,
  "email_expiration_time": 600,
  "email_token_size": 6,
  "emergency_access_allowed": true,
  "emergency_notification_reminder_schedule": "0 3 * * * *",
  "emergency_request_timeout_schedule": "0 7 * * * *",
  "enable_db_wal": true,
  "enable_websocket": true,
  "enforce_single_org_with_reset_pw_policy": false,
  "event_cleanup_schedule": "0 10 0 * * *",
  "events_days_retain": null,
  "experimental_client_feature_flags": "ssh-key-vault-item,ssh-agent,fido2-vault-credentials",
  "extended_logging": true,
  "helo_name": null,
  "hibp_api_key": null,
  "http_request_block_non_global_ips": false,
  "http_request_block_regex": "^(127\\.)|^(192\\.168\\.)|^(10\\.)|^(172\\.1[6-9]\\.)|^(172\\.2[0-9]\\.)|^(172\\.3[0-1]\\.)|(\\.arpa)$|(\\.local)$",
  "icon_blacklist_non_global_ips": false,
  "icon_blacklist_regex": "^(127\\.)|^(192\\.168\\.)|^(10\\.)|^(172\\.1[6-9]\\.)|^(172\\.2[0-9]\\.)|^(172\\.3[0-1]\\.)|(\\.arpa)$|(\\.local)$",
  "icon_cache_folder": "data/icon_cache",
  "icon_cache_negttl": 259200,
  "icon_cache_ttl": 2592000,
  "icon_download_timeout": 10,
  "icon_redirect_code": 301,
  "icon_service": "google",
  "incomplete_2fa_schedule": "30 * * * * *",
  "incomplete_2fa_time_limit": 3,
  "increase_note_size_limit": false,
  "invitation_expiration_hours": 120,
  "invitation_org_name": "Vaultwarden",
  "invitations_allowed": true,
  "ip_header": "X-Real-IP",
  "job_poll_interval_ms": 30000,
  "log_file": null,
  "log_level": "warn",
  "log_timestamp_format": "%Y-%m-%d %H:%M:%S.%3f",
  "login_ratelimit_max_burst": 10,
  "login_ratelimit_seconds": 60,
  "org_attachment_limit": null,
  "org_creation_users": "",
  "org_events_enabled": false,
  "org_groups_enabled": false,
  "password_hints_allowed": true,
  "password_iterations": 600000,
  "push_enabled": true,
  "push_identity_uri": "https://identity.bitwarden.com",
  "push_installation_id": "***",
  "push_installation_key": "***",
  "push_relay_uri": "https://push.bitwarden.com",
  "reload_templates": false,
  "require_device_email": false,
  "rsa_key_filename": "data/rsa_key",
  "send_purge_schedule": "0 5 * * * *",
  "sendmail_command": null,
  "sends_allowed": true,
  "sends_folder": "data/sends",
  "show_password_hint": false,
  "signups_allowed": false,
  "signups_domains_whitelist": "",
  "signups_verify": true,
  "signups_verify_resend_limit": 6,
  "signups_verify_resend_time": 3600,
  "smtp_accept_invalid_certs": false,
  "smtp_accept_invalid_hostnames": false,
  "smtp_auth_mechanism": "Login",
  "smtp_debug": false,
  "smtp_embed_images": true,
  "smtp_explicit_tls": null,
  "smtp_from": "*********************",
  "smtp_from_name": "Vaultwarden",
  "smtp_host": "**************",
  "smtp_password": "***",
  "smtp_port": 465,
  "smtp_security": "force_tls",
  "smtp_ssl": null,
  "smtp_timeout": 15,
  "smtp_username": "***********",
  "templates_folder": "data/templates",
  "tmp_folder": "data/tmp",
  "trash_auto_delete_days": null,
  "trash_purge_schedule": "0 5 0 * * *",
  "use_sendmail": false,
  "use_syslog": false,
  "user_attachment_limit": null,
  "user_send_limit": null,
  "web_vault_enabled": true,
  "web_vault_folder": "web-vault/",
  "yubico_client_id": null,
  "yubico_secret_key": null,
  "yubico_server": null
}
```

</details>

### Vaultwarden Build Version

1.33.1

### Deployment method

Official Container Image

### Custom deployment method

_No response_

### Reverse Proxy

nginx 

### Host/Server Operating System

Linux

### Operating System Version

_No response_

### Clients

Browser Extension, Desktop

### Client Version

_No response_

### Steps To Reproduce

1. Update vaultwarden to 1.33.1
2. Go to web extension or desktop client and check icons

### Expected Result

Icons are loaded for items with URL

### Actual Result

Icons not loaded

### Logs

```text

```

### Screenshots or Videos

_No response_

### Additional Context

After update to 1.33.1 still have icon issue. The reason - Cross-Origin-Resource-Policy header. According to [PR](https://github.com/dani-garcia/vaultwarden/pull/5469) Cross-Origin-Resource-Policy header should be added to any response except content-type: image.  But i use   301 redirect to google to provide icons for clients and header Cross-Origin-Resource-Policy still present and browser extension and desktop client refuse to load icons.

### PR DESCRIPTION
**Pull request by BlackDex**
We also need to exclude the header in case we do an external_icon call.

Fixes #5535

### CODE REVIEW

File: src/util.rs [hunk 1]
```diff
@@ -56,13 +56,17 @@ impl Fairing for AppHeaders {
...
-        if !res.headers().get_one("Content-Type").is_some_and(|v| v.starts_with("image/")) {
-            res.set_raw_header("Cross-Origin-Resource-Policy", "same-origin");
-        }
-
         // Obsolete in modern browsers, unsafe (XS-Leak), and largely replaced by CSP
         res.set_raw_header("X-XSS-Protection", "0");
 
+        // The `Cross-Origin-Resource-Policy` header should not be set on images or on the `icon_external` route.
+        // Else some clients, like the Bitwardem Desktop will fail to download the icons
+        if !(res.headers().get_one("Content-Type").is_some_and(|v| v.starts_with("image/"))
```
Comment (dani-garcia) [inline src/util.rs:64]: Probably a good idea to add a comment on `icon_external` in case we rename it in the future.

File: src/util.rs [hunk 2]
```diff
@@ -56,13 +56,17 @@ impl Fairing for AppHeaders {
...
 
-        if !res.headers().get_one("Content-Type").is_some_and(|v| v.starts_with("image/")) {
-            res.set_raw_header("Cross-Origin-Resource-Policy", "same-origin");
-        }
-
         // Obsolete in modern browsers, unsafe (XS-Leak), and largely replaced by CSP
         res.set_raw_header("X-XSS-Protection", "0");
 
+        // The `Cross-Origin-Resource-Policy` header should not be set on images or on the `icon_external` route.
+        // Else some clients, like the Bitwardem Desktop will fail to download the icons
```
Comment (tessus) [inline src/util.rs:63]:
```suggestion
        // Otherwise some clients, like the Bitwardem Desktop, will fail to download the icons
```

Updated the wording and a comma was missing.

Comment (Gerardv514) [inline src/util.rs:63]:
```suggestion
        // Else some clients, like the Bitwarden Desktop will fail to download the icons
```

**Review by Gerardv514 — APPROVED** [review]

**Review by tessus — APPROVED** [review]

**Review by dani-garcia — APPROVED** [review]
