### PR TITLE
Fix Vaultwarden Admin page error messages

### LINKED ISSUE #4834: Bad request if config is not read/writeable
I migrated from a docker container to an LCX container. Therefore, I moved the data to the new system.
Everything was updated with the correct owner, just the config.json was not changed to the correct owner.

During changing data in the admin-area, the save throws and "400 Bad Request", but the UI shows, that the changed are there (also after a force refresh). The changed settings are active, until I update to the next version.

After chaning the owner to the correct user, saving is working.

I would recommend, that the response contain an information, that the config file is not writeable.

### PR DESCRIPTION
**Pull request by BlackDex**
Since the change to camelCase variables the error messages in the Vaultwarden Admin were not shown correctly anymore.

This PR fixes this by changing the case of the json key's. Also updated the save and delete of the config to provide a more descriptive error instead of only `Io` or which ever other error might occure.

Fixes #4834

### CODE REVIEW

File: src/api/admin.rs [hunk 1]
```diff
@@ -750,12 +750,19 @@ fn get_diagnostics_config(_token: AdminToken) -> Json<Value> {
...
+        err!(format!("Unable to save config: {e:?}"))
+    }
+    Ok(())
 }
 
 #[post("/config/delete")]
 fn delete_config(_token: AdminToken) -> EmptyResult {
-    CONFIG.delete_user_config()
+    if let Err(e) = CONFIG.delete_user_config() {
+        dbg!(e.to_string());
```
Comment (tessus) [inline src/api/admin.rs:762]:
```suggestion
```

This seems like an oversight. e.g. there is no `dbg!` in `post_config`.

Comment (BlackDex) [reply src/api/admin.rs]: good catch.

**Review by dani-garcia — APPROVED** [review]
