### PR TITLE
Make sure the icons are displayed correctly in desktop clients

### LINKED ISSUE #5452: No Icons in Desktop Clients with Vaultwarden 1.33.0
### Your environment (Generated via diagnostics page)

* Vaultwarden version: v1.33.0
* Web-vault version: v2025.1.1
* OS/Arch: linux/x86_64
* Running within a container: true (Base: Debian)
* Database type: MySQL
* Database version: 8.0.41
* Environment settings overridden!: false
* Uses a reverse proxy: true
* IP Header check: true (x-forwarded-for)
* Internet access: true
* Internet access via a proxy: false
* DNS Check: true
* Browser/Server Time Check: true
* Server/NTP Time Check: true
* Domain Configuration Check: true
* HTTPS Check: true
* Websocket Check: true
* HTTP Response Checks: true

### Config & Details (Generated via diagnostics page)

<details><summary>Show Config & Details</summary>

**Config:**

```json
{
  "_duo_akey": null,
  "_enable_duo": false,
  "_enable_email_2fa": false,
  "_enable_smtp": true,
  "_enable_yubico": true,
  "_icon_service_csp": "",
  "_icon_service_url": "",
  "_ip_header_enabled": true,
  "_max_note_size": 10000,
  "_smtp_img_src": "***:",
  "admin_ratelimit_max_burst": 3,
  "admin_ratelimit_seconds": 300,
  "admin_session_lifetime": 20,
  "admin_token": "***",
  "allowed_connect_src": "",
  "allowed_iframe_ancestors": "",
  "attachments_folder": "data/attachments",
  "auth_request_purge_schedule": "30 * * * * *",
  "authenticator_disable_time_drift": false,
  "data_folder": "data",
  "database_conn_init": "",
  "database_max_conns": 10,
  "database_timeout": 30,
  "database_url": "*****://*******************************************************************",
  "db_connection_retries": 15,
  "disable_2fa_remember": false,
  "disable_admin_token": false,
  "disable_icon_download": false,
  "domain": "*****://******************",
  "domain_origin": "*****://******************",
  "domain_path": "",
  "domain_set": true,
  "duo_context_purge_schedule": "30 * * * * *",
  "duo_host": "api-bc8d4d38.duosecurity.com",
  "duo_ikey": "DICFPHD0UJEWUVKIKAVM",
  "duo_skey": "***",
  "duo_use_iframe": false,
  "email_2fa_auto_fallback": false,
  "email_2fa_enforce_on_verified_invite": false,
  "email_attempts_limit": 3,
  "email_change_allowed": true,
  "email_expiration_time": 600,
  "email_token_size": 6,
  "emergency_access_allowed": true,
  "emergency_notification_reminder_schedule": "0 3 * * * *",
  "emergency_request_timeout_schedule": "0 7 * * * *",
  "enable_db_wal": true,
  "enable_websocket": true,
  "enforce_single_org_with_reset_pw_policy": false,
  "event_cleanup_schedule": "0 10 0 * * *",
  "events_days_retain": null,
  "experimental_client_feature_flags": "fido2-vault-credentials",
  "extended_logging": true,
  "helo_name": null,
  "hibp_api_key": null,
  "http_request_block_non_global_ips": true,
  "http_request_block_regex": null,
  "icon_blacklist_non_global_ips": true,
  "icon_blacklist_regex": null,
  "icon_cache_folder": "data/icon_cache",
  "icon_cache_negttl": 259200,
  "icon_cache_ttl": 2592000,
  "icon_download_timeout": 10,
  "icon_redirect_code": 302,
  "icon_service": "internal",
  "incomplete_2fa_schedule": "30 * * * * *",
  "incomplete_2fa_time_limit": 3,
  "increase_note_size_limit": false,
  "invitation_expiration_hours": 120,
  "invitation_org_name": "Miller Family Password Vault",
  "invitations_allowed": true,
  "ip_header": "x-forwarded-for",
  "job_poll_interval_ms": 30000,
  "log_file": "/data/vaultwarden.log",
  "log_level": "info",
  "log_timestamp_format": "%Y-%m-%d %H:%M:%S.%3f",
  "login_ratelimit_max_burst": 10,
  "login_ratelimit_seconds": 60,
  "org_attachment_limit": null,
  "org_creation_users": "",
  "org_events_enabled": false,
  "org_groups_enabled": false,
  "password_hints_allowed": true,
  "password_iterations": 1000000,
  "push_enabled": true,
  "push_identity_uri": "https://identity.bitwarden.com",
  "push_installation_id": "***",
  "push_installation_key": "***",
  "push_relay_uri": "https://push.bitwarden.com",
  "reload_templates": false,
  "require_device_email": false,
  "rsa_key_filename": "data/rsa_key",
  "send_purge_schedule": "0 5 * * * *",
  "sendmail_command": null,
  "sends_allowed": true,
  "sends_folder": "data/sends",
  "show_password_hint": false,
  "signups_allowed": false,
  "signups_domains_whitelist": "",
  "signups_verify": true,
  "signups_verify_resend_limit": 6,
  "signups_verify_resend_time": 3600,
  "smtp_accept_invalid_certs": false,
  "smtp_accept_invalid_hostnames": false,
  "smtp_auth_mechanism": "off",
  "smtp_debug": false,
  "smtp_embed_images": true,
  "smtp_explicit_tls": null,
  "smtp_from": "******************",
  "smtp_from_name": "MillerNet Password Vault",
  "smtp_host": "*****************",
  "smtp_password": null,
  "smtp_port": 587,
  "smtp_security": "off",
  "smtp_ssl": null,
  "smtp_timeout": 15,
  "smtp_username": null,
  "templates_folder": "data/templates",
  "tmp_folder": "data/tmp",
  "trash_auto_delete_days": null,
  "trash_purge_schedule": "0 5 0 * * *",
  "use_sendmail": false,
  "use_syslog": false,
  "user_attachment_limit": null,
  "user_send_limit": null,
  "web_vault_enabled": true,
  "web_vault_folder": "web-vault/",
  "yubico_client_id": "102714",
  "yubico_secret_key": "***",
  "yubico_server": null
}
```

</details>

### Vaultwarden Build Version

1.33.0

### Deployment method

Official Container Image

### Custom deployment method

_No response_

### Reverse Proxy

Caddy v2.9.1

### Host/Server Operating System

NAS/SAN

### Operating System Version

macOS 12.7.6

### Clients

Desktop

### Client Version

2025.1.3

### Steps To Reproduce

1. Open Bitwarden client
2. View any or all entries in the vault
3. File -> Sync
4. Still no icons

### Expected Result

Icons for websites.

### Actual Result

a mixture of the default no icon and a broken image.

### Logs

```text

```

### Screenshots or Videos

Image

Reverting to 1.32.7 restores the icons.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by WinLinux1028**
Fixes #5452

### CODE REVIEW

File: src/util.rs [hunk 1]
```diff
@@ -55,7 +55,9 @@ impl Fairing for AppHeaders {
         res.set_raw_header("Referrer-Policy", "same-origin");
         res.set_raw_header("X-Content-Type-Options", "nosniff");
         res.set_raw_header("X-Robots-Tag", "noindex, nofollow");
-        res.set_raw_header("Cross-Origin-Resource-Policy", "same-origin");
+        if !(req_uri_path.starts_with("/icons/") && req_uri_path.ends_with("/icon.png")) {
```
Comment (BlackDex) [inline src/util.rs:58]: I think we only need to check if it ends with `/icon.png`.
The other check is not really needed and might even not work if someone uses a sub-path to host Vaultwarden on.

**Review by BlackDex — CHANGES_REQUESTED** [review]

File: src/util.rs [hunk 2]
```diff
@@ -55,7 +55,9 @@ impl Fairing for AppHeaders {
...
+            res.set_raw_header("Cross-Origin-Resource-Policy", "same-origin");
+        }
```
Comment (tessus) [inline src/util.rs:60]: I'd go with the same process as above (might even be slightly more performant):

```suggestion
        res.set_raw_header("Cross-Origin-Resource-Policy", "same-origin");
        if req_uri_path.ends_with("/icon.png") {
            res.remove_header("Cross-Origin-Resource-Policy");
        }
```

File: src/util.rs (hunk 1 above)
Comment (WinLinux1028) [reply src/util.rs]: I was adding this check because I thought there might be other paths that end in `icon.png`.
I deleted it as it was unnecessary.

File: src/util.rs (hunk 2 above)
Comment (BlackDex) [reply src/util.rs]: How would this be more performant?
You first always set the header, then always check if it ends on a specific string.
While you can also negate the check if it always ends on a specific string and then just set the header.

Comment (jjlin) [reply src/util.rs]: Why would it be more performant to set a header and then potentially remove it? Seems like it would be simplest just to do
```
if !req_uri_path.ends_with("/icon.png") {
    res.set_raw_header("Cross-Origin-Resource-Policy", "same-origin");
}
```

File: src/util.rs [hunk 3]
```diff
@@ -57,6 +57,10 @@ impl Fairing for AppHeaders {
         res.set_raw_header("X-Robots-Tag", "noindex, nofollow");
         res.set_raw_header("Cross-Origin-Resource-Policy", "same-origin");
 
+        if req_uri_path.ends_with("/icon.png") {
+            res.remove_header("Cross-Origin-Resource-Policy");
+        }
+
```
[the remark this answers is not in the document]
Comment (WinLinux1028) [reply src/util.rs:63]: There seems to be a conflict of opinion.
@tessus How do you think about this?

[the remark this answers is not in the document]
Comment (tessus) [reply src/util.rs:63]: @BlackDex in the4 code above the headers are removed when a condition is met. The question is whether most of the calls are calls that end in icon.png or not.
If other calls are more likely, removing the header is better for performance

File: src/util.rs (hunk 2 above)
Comment (tessus) [reply src/util.rs]: branch prediction. but maybe not anymore. maybe the compilers are much better these days. I am probably too old....

Comment (tessus) [reply src/util.rs]: also, I have noticed that in some projects clippy will complain because clippy prefers matches over not matches. But maybe that's not the case here either

File: src/util.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (BlackDex) [reply src/util.rs:63]: If you are referring to the `notifications/hub` checks, those do an early return.

It doesn't matter if most of the calls end with `/icon.png` or not, the check is done always not matter if you put a `!` in-front of it or not.

In your example there is always 1 call extra, the removing of a just added header, which to me is illogical.
Only set it when needed, and not set it, and then afterwards say, ow wait, i do not need it anyway, lets do an other function call to delete it again.

[the remark this answers is not in the document]
Comment (tessus) [reply src/util.rs:63]: It's your decision of course. I am way past my bed time, so I am heading to bed now.

File: src/util.rs (hunk 1 above)
Comment (WinLinux1028) [reply src/util.rs]:
```Rust
        if let Some(path_stripped) = req_uri_path.as_str().strip_prefix(CONFIG.domain_path()) {
            if !(path_stripped.starts_with("/icons/") && path_stripped.ends_with("/icon.png")) {
                res.set_raw_header("Cross-Origin-Resource-Policy", "same-origin");
            }
        }
```
How about doing it like this?

File: src/util.rs (hunk 2 above)
Comment (BlackDex) [reply src/util.rs]: The clippy lint gets triggered if there would have been a function `not_ends_with()` which makes it more clear because missing the `!` in front is easier to do, and a function with that name is more descriptive.

And, doesn't branch prediction work the same way for the exclusion? If the CPU can predict when to not call it, that is fine too ;)

File: src/util.rs (hunk 1 above)
Comment (BlackDex) [reply src/util.rs]: That is overly complicated, and not needed, as there only is one valid path which ends on `/icon.png`

So, only checking if the path doesn't end on it will be fine.

**Review by BlackDex — DISMISSED** [review]

File: src/util.rs [hunk 4]
```diff
@@ -55,7 +55,9 @@ impl Fairing for AppHeaders {
         res.set_raw_header("Referrer-Policy", "same-origin");
         res.set_raw_header("X-Content-Type-Options", "nosniff");
         res.set_raw_header("X-Robots-Tag", "noindex, nofollow");
-        res.set_raw_header("Cross-Origin-Resource-Policy", "same-origin");
+        if !req_uri_path.ends_with("/icon.png") {
+            res.set_raw_header("Cross-Origin-Resource-Policy", "same-origin");
+        }
```
Comment (stefan0xC) [inline src/util.rs:60]: Isn't something like that also needed for "mail-github.png" and "logo-gray.png" in case `SMTP_EMBED_IMAGES=false` (so they can be fetched by mail clients)? Something like
```suggestion
        if !(req_uri_path.ends_with("/icon.png")
             || (!CONFIG.smtp_embed_images
                && (req_uri_path.ends_with("/logo-gray.png")
                || req_uri_path.ends_with("/mail-github.png"))) {
            res.set_raw_header("Cross-Origin-Resource-Policy", "same-origin");
        }
```

Comment (BlackDex) [reply src/util.rs:60]: Hmmm, i have not tested that yet to be fair.
But then only excluding those files will probably still cause issues, since you could server custom image files too, not just those we set our self.

Comment (BlackDex) [reply src/util.rs:60]: I think there is a better way.

Comment (WinLinux1028) [reply src/util.rs:60]: After checking the email I received from Vaultwarden, I found that the two files are under `/vw_static/`.
How about doing it like this?

```Rust
if let Some(path_stripped) = req_uri_path.strip_prefix(&*CONFIG.domain_path()) {
    if !(path_stripped.starts_with("/icons/") || path_stripped.starts_with("/vw_static/") {
        res.set_raw_header("Cross-Origin-Resource-Policy", "same-origin");
    }
}
```

Comment (stefan0xC) [reply src/util.rs:60]: Sounds good. I mean, if we want to tackle this in a separate PR this would be fine for me too.

**Review by stefan0xC — APPROVED** [review]

File: src/util.rs (hunk 4 above)
Comment (BlackDex) [reply src/util.rs:60]: We can use `res.content_type()` and check if it is an image :)

Comment (WinLinux1028) [reply src/util.rs]: Isn't it too much to not apply `Cross-Origin-Resource-Policy` to all images?

File: src/util.rs [hunk 5]
```diff
@@ -55,7 +55,12 @@ impl Fairing for AppHeaders {
         res.set_raw_header("Referrer-Policy", "same-origin");
         res.set_raw_header("X-Content-Type-Options", "nosniff");
         res.set_raw_header("X-Robots-Tag", "noindex, nofollow");
-        res.set_raw_header("Cross-Origin-Resource-Policy", "same-origin");
+
+        if let Some(path_stripped) = req_uri_path.strip_prefix(&*CONFIG.domain_path()) {
+            if !(path_stripped.starts_with("/icons/") || path_stripped.starts_with("/vw_static/")) {
+                res.set_raw_header("Cross-Origin-Resource-Policy", "same-origin");
+            }
+        }
```
Comment (stefan0xC) [inline src/util.rs:63]: I think I'd also prefer @BlackDex suggestion. I.e, something like:
```suggestion
        if !res.is_png() {
            res.set_raw_header("Cross-Origin-Resource-Policy", "same-origin");
        }
```

File: src/util.rs (hunk 4 above)
Comment (BlackDex) [reply src/util.rs]: I think we could use `res.headers().get_one("Content-Type").is_some_and(|v| v.starts_with("image"))` which should solve it.

Well, what if someone uses a modified image from the web-vault somewhere? Like browsers might use it for the favicon of the domain for example?

It's not that the images really need protection from being fetched in my opinion.
But more to prevent other scripts or sites from being able to abuse the API endpoints.

File: src/util.rs (hunk 5 above)
Comment (WinLinux1028) [reply src/util.rs:63]: What about non-PNG images?
In my opinion, it's too much to not apply Cross-Origin-Resource-Policy to all images.

Comment (BlackDex) [reply src/util.rs:63]:
```suggestion
        if !res.headers().get_one("Content-Type").is_some_and(|v| v.starts_with("image")) {
            res.set_raw_header("Cross-Origin-Resource-Policy", "same-origin");
        }
```

Comment (stefan0xC) [reply src/util.rs:63]: I don't think that we can have it both ways without complicating the this further. I think allowing only `PNG` should be enough. (If you don't agree, I've also posted an suggestion above https://github.com/dani-garcia/vaultwarden/pull/5469#discussion_r1930244657 which would only allow the bare minimum.)

Comment (WinLinux1028) [reply src/util.rs:63]: In the future, we may use WebP or AVIF, so [this](https://github.com/dani-garcia/vaultwarden/pull/5469#discussion_r1930318145) method is a good choice if you do not want to assign Cross-Origin-Resource-Policy to all images.

Comment (BlackDex) [reply src/util.rs]: That isn't possible. The content type is based upon the image type by it's headers. And thus not only `PNG` types are returned.

https://github.com/dani-garcia/vaultwarden/blob/2903a3a13ad06a09805e8842511b4b715a686d8e/src/api/icons.rs#L582-L592

Comment (BlackDex) [reply src/util.rs]: And:
https://github.com/dani-garcia/vaultwarden/blob/2903a3a13ad06a09805e8842511b4b715a686d8e/src/api/icons.rs#L113-L119

**Review by BlackDex — APPROVED** [review]

**Review by dani-garcia — APPROVED** [review]

**Comment by Livefour2day** [comment]
Icon issue in Chrome extension and desktop still present after latest update.

**Comment by BlackDex** [comment]
> Missing icons issue in Chrome extension and desktop still present after latest update.

Are you using icon redirects?

**Comment by Livefour2day** [comment]
> > Missing icons issue in Chrome extension and desktop still present after latest update.
> 
> Are you using icon redirects?

Yes is this the issue it has been working fine for years

**Comment by BlackDex** [comment]
> > > Missing icons issue in Chrome extension and desktop still present after latest update.
> > 
> > 
> > Are you using icon redirects?
> 
> Yes is this the issue it has been working fine for years

This is fixed via #5536
